# Generated by Django 4.2.9 on 2025-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='visit',
            name='clicked_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_returning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='visit',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Seconds spent on previous page'),
        ),
        migrations.AddField(
            model_name='visit',
            name='traffic_source',
            field=models.CharField(blank=True, help_text='google, direct, facebook, etc.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['created_at'], name='core_visit_created_4d6338_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['session_key', 'created_at'], name='core_visit_session_dd9f0a_idx'),
        ),
    ]
