# Generated by Django 4.2.9 on 2025-12-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_visit_options_visit_clicked_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='device_type',
            field=models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['country'], name='core_visit_country_869e90_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['device_type'], name='core_visit_device__9437cb_idx'),
        ),
    ]
